### ISSUE TITLE
cffi installation broken (Ubuntu 12.04)

### ISSUE THREAD

**Issue by mhils** [mitmproxy/netlib#32]
Reported by thom_ in #mitmproxy.

Clean Ubuntu 12.04 installation:
<pre>
$ sudo apt-get install git
$ sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip
$ sudo pip install --upgrade git+https://github.com/mitmproxy/netlib.git
$ python
>>> from netlib import certffi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/netlib/certffi.py", line 18, in <module>
    extra_compile_args=['-w']
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 341, in verify
    lib = self.verifier.load_library()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 73, in load_library
    self._write_source()
  File "/usr/local/lib/python2.7/dist-packages/cffi/verifier.py", line 125, in _write_source
    file = open(self.sourcefilename, 'w')
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/netlib/__pycache__/_cffi__x6e59bce0x94e38fe2.c'
</pre>

Temporary workaround:
<pre>
$ sudo python
>>> from netlib import certffi
>>> exit()  # works without sudo now
</pre>

**Comment by Kriechi** [comment]
I tried to tackle this in a simple way. Maybe someone can use it or come up with a better/cleaner way:
https://github.com/Kriechi/netlib/tree/distribute-cffi
